// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// frobenius_inner_product
double frobenius_inner_product(S4 A, S4 B, Rcpp::Nullable<Rcpp::S4> C);
RcppExport SEXP _mvREHE_frobenius_inner_product(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type A(ASEXP);
    Rcpp::traits::input_parameter< S4 >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::S4> >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(frobenius_inner_product(A, B, C));
    return rcpp_result_gen;
END_RCPP
}
// compute_WDY
arma::mat compute_WDY(S4 D, S4 W, const arma::mat& Y);
RcppExport SEXP _mvREHE_compute_WDY(SEXP DSEXP, SEXP WSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type D(DSEXP);
    Rcpp::traits::input_parameter< S4 >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_WDY(D, W, Y));
    return rcpp_result_gen;
END_RCPP
}
// compute_Y_tilde
arma::vec compute_Y_tilde(const arma::mat& Y, const arma::vec row_indices, const arma::vec col_indices, int j, int m);
RcppExport SEXP _mvREHE_compute_Y_tilde(SEXP YSEXP, SEXP row_indicesSEXP, SEXP col_indicesSEXP, SEXP jSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type row_indices(row_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type col_indices(col_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Y_tilde(Y, row_indices, col_indices, j, m));
    return rcpp_result_gen;
END_RCPP
}
// compute_W_sparse
S4 compute_W_sparse(S4 R, S4 R2, NumericVector R_diag, NumericVector R2_diag, double h2, double rho_g, double rho_e, double N, double M_snps);
RcppExport SEXP _mvREHE_compute_W_sparse(SEXP RSEXP, SEXP R2SEXP, SEXP R_diagSEXP, SEXP R2_diagSEXP, SEXP h2SEXP, SEXP rho_gSEXP, SEXP rho_eSEXP, SEXP NSEXP, SEXP M_snpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type R(RSEXP);
    Rcpp::traits::input_parameter< S4 >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R_diag(R_diagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R2_diag(R2_diagSEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type rho_g(rho_gSEXP);
    Rcpp::traits::input_parameter< double >::type rho_e(rho_eSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type M_snps(M_snpsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_W_sparse(R, R2, R_diag, R2_diag, h2, rho_g, rho_e, N, M_snps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvREHE_frobenius_inner_product", (DL_FUNC) &_mvREHE_frobenius_inner_product, 3},
    {"_mvREHE_compute_WDY", (DL_FUNC) &_mvREHE_compute_WDY, 3},
    {"_mvREHE_compute_Y_tilde", (DL_FUNC) &_mvREHE_compute_Y_tilde, 5},
    {"_mvREHE_compute_W_sparse", (DL_FUNC) &_mvREHE_compute_W_sparse, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvREHE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
