// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loss
double loss(const List& Y_tilde_list, const arma::mat& X_tilde, const List& L_list, double lambda);
RcppExport SEXP _mvREHE_loss(SEXP Y_tilde_listSEXP, SEXP X_tildeSEXP, SEXP L_listSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Y_tilde_list(Y_tilde_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tilde(X_tildeSEXP);
    Rcpp::traits::input_parameter< const List& >::type L_list(L_listSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(loss(Y_tilde_list, X_tilde, L_list, lambda));
    return rcpp_result_gen;
END_RCPP
}
// loss2
double loss2(const List& Y_tilde_list, const arma::mat& X_tilde, const List& Sigma_list);
RcppExport SEXP _mvREHE_loss2(SEXP Y_tilde_listSEXP, SEXP X_tildeSEXP, SEXP Sigma_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Y_tilde_list(Y_tilde_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tilde(X_tildeSEXP);
    Rcpp::traits::input_parameter< const List& >::type Sigma_list(Sigma_listSEXP);
    rcpp_result_gen = Rcpp::wrap(loss2(Y_tilde_list, X_tilde, Sigma_list));
    return rcpp_result_gen;
END_RCPP
}
// gradient_full
void gradient_full(const List& Y_tilde_list, const arma::mat& X_tilde, const List& L_list, List& gradient_list, double lambda);
RcppExport SEXP _mvREHE_gradient_full(SEXP Y_tilde_listSEXP, SEXP X_tildeSEXP, SEXP L_listSEXP, SEXP gradient_listSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Y_tilde_list(Y_tilde_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tilde(X_tildeSEXP);
    Rcpp::traits::input_parameter< const List& >::type L_list(L_listSEXP);
    Rcpp::traits::input_parameter< List& >::type gradient_list(gradient_listSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    gradient_full(Y_tilde_list, X_tilde, L_list, gradient_list, lambda);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvREHE_loss", (DL_FUNC) &_mvREHE_loss, 4},
    {"_mvREHE_loss2", (DL_FUNC) &_mvREHE_loss2, 3},
    {"_mvREHE_gradient_full", (DL_FUNC) &_mvREHE_gradient_full, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvREHE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
