# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss <- function(Y_tilde_list, X_tilde, L_list, lambda) {
    .Call('_mvREHE_loss', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, L_list, lambda)
}

loss2 <- function(Y_tilde_list, X_tilde, Sigma_list) {
    .Call('_mvREHE_loss2', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, Sigma_list)
}

loss3 <- function(Y, X_tilde, Sigma_list, lambda) {
    .Call('_mvREHE_loss3', PACKAGE = 'mvREHE', Y, X_tilde, Sigma_list, lambda)
}

gradient_full <- function(Y_tilde_list, X_tilde, L_list, gradient_list, lambda) {
    invisible(.Call('_mvREHE_gradient_full', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, L_list, gradient_list, lambda))
}

compute_W_list <- function(Y, D_list, W_list) {
    invisible(.Call('_mvREHE_compute_W_list', PACKAGE = 'mvREHE', Y, D_list, W_list))
}

