# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss <- function(Y_tilde_list, X_tilde, L_list) {
    .Call('_mvREHE_loss', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, L_list)
}

loss2 <- function(Y_tilde_list, X_tilde, Sigma_list) {
    .Call('_mvREHE_loss2', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, Sigma_list)
}

gradient_full <- function(Y_tilde_list, X_tilde, L_list, gradient_list) {
    invisible(.Call('_mvREHE_gradient_full', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, L_list, gradient_list))
}

fit_GD <- function(Y_tilde_list, X_tilde, max_iter, tolerance, L_list, gradient_list) {
    .Call('_mvREHE_fit_GD', PACKAGE = 'mvREHE', Y_tilde_list, X_tilde, max_iter, tolerance, L_list, gradient_list)
}

