# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loss3 <- function(Y, X_tilde, Sigma_list, lambda) {
    .Call('_mvREHE_loss3', PACKAGE = 'mvREHE', Y, X_tilde, Sigma_list, lambda)
}

compute_W_list <- function(Y, D_list, W_list) {
    invisible(.Call('_mvREHE_compute_W_list', PACKAGE = 'mvREHE', Y, D_list, W_list))
}

